pipeline:
    name: SamplePipelineFromYaml
    steps:         
        TrainStep:
            python_script_step:
                type: "PythonScriptStep"
                script_name: "train.py"
                allow_reuse: True
                source_directory: "."
            runconfig: 'aml_config/train.runconfig'
            outputs:
                result:
                    destination: Output
                    datastore: workspaceblobstore
                    type: mount
